/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoCliente;
import fatec.poo.control.DaoItemPedido;
import fatec.poo.control.DaoPedido;
import fatec.poo.control.DaoProduto;
import fatec.poo.control.DaoVendedor;
import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Random;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class GuiEmitirPedido extends javax.swing.JFrame {

	/**
	 * Creates new form GuiEmitirPedido
	 */
	public GuiEmitirPedido() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		groupFormaPagamento = new javax.swing.ButtonGroup();
		btnIncluir = new javax.swing.JButton();
		btnAlterar = new javax.swing.JButton();
		btnExcluir = new javax.swing.JButton();
		btnSair = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txtNumPedido = new javax.swing.JTextField();
		btnConsultarPed = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		txtfDtPedido = new javax.swing.JFormattedTextField();
		jPanel5 = new javax.swing.JPanel();
		rbtnAVista = new javax.swing.JRadioButton();
		rbtnAPrazo = new javax.swing.JRadioButton();
		jPanel2 = new javax.swing.JPanel();
		txtfCPFCli = new javax.swing.JFormattedTextField();
		jLabel2 = new javax.swing.JLabel();
		lblCliente = new javax.swing.JLabel();
		btnConsultarCli = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		txtfCPFVend = new javax.swing.JFormattedTextField();
		lblVendedor = new javax.swing.JLabel();
		btnConsultarVen = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		lblProduto = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtCodProduto = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		btnAddItem = new javax.swing.JButton();
		btnRemoverItem = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblItens = new javax.swing.JTable();
		lblValTotPedido = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		lblQtdItensPedido = new javax.swing.JLabel();
		txtQtdItensPedido = new javax.swing.JTextField();
		btnConsultarPro = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Emitir Pedido");
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		btnIncluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/add.png"))); // NOI18N
		btnIncluir.setText("Incluir");
		btnIncluir.setEnabled(false);
		btnIncluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIncluirActionPerformed(evt);
			}
		});

		btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/Alterar.png"))); // NOI18N
		btnAlterar.setText("Alterar");
		btnAlterar.setEnabled(false);
		btnAlterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAlterarActionPerformed(evt);
			}
		});

		btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/Eraser.png"))); // NOI18N
		btnExcluir.setText("Excluir");
		btnExcluir.setEnabled(false);
		btnExcluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExcluirActionPerformed(evt);
			}
		});

		btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/exit.png"))); // NOI18N
		btnSair.setText("Sair");
		btnSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSairActionPerformed(evt);
			}
		});

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 12))); // NOI18N
		jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("Número do Pedido");

		txtNumPedido.setToolTipText("");

		btnConsultarPed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnConsultarPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/pesq.png"))); // NOI18N
		btnConsultarPed.setMaximumSize(new java.awt.Dimension(49, 20));
		btnConsultarPed.setMinimumSize(new java.awt.Dimension(49, 20));
		btnConsultarPed.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarPedActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("Data do Pedido");

		try {
			txtfDtPedido.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtfDtPedido.setEnabled(false);

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));
		jPanel5.setToolTipText("Forma de Pagamento");

		groupFormaPagamento.add(rbtnAVista);
		rbtnAVista.setSelected(true);
		rbtnAVista.setText("À Vista");
		rbtnAVista.setEnabled(false);

		groupFormaPagamento.add(rbtnAPrazo);
		rbtnAPrazo.setText("A Prazo");
		rbtnAPrazo.setEnabled(false);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addComponent(rbtnAVista)
								.addGap(18, 18, Short.MAX_VALUE)
								.addComponent(rbtnAPrazo)
								.addGap(30, 30, 30)));
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(rbtnAVista)
										.addComponent(rbtnAPrazo))));

		rbtnAVista.getAccessibleContext().setAccessibleDescription("");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 144,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnConsultarPed, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(30, 30, 30)
								.addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(txtfDtPedido)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnConsultarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel4)
												.addComponent(txtfDtPedido, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 11, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Cliente",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 12))); // NOI18N

		try {
			txtfCPFCli.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtfCPFCli.setEnabled(false);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("CPF Cliente");

		lblCliente.setText(" ");
		lblCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		btnConsultarCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnConsultarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/pesq.png"))); // NOI18N
		btnConsultarCli.setEnabled(false);
		btnConsultarCli.setMaximumSize(new java.awt.Dimension(49, 20));
		btnConsultarCli.setMinimumSize(new java.awt.Dimension(49, 20));
		btnConsultarCli.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarCliActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2)
								.addGap(30, 30, 30)
								.addComponent(txtfCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, 125,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(39, 39, 39)
								.addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGap(15, 15, 15)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(txtfCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(lblCliente, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnConsultarCli,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addContainerGap(15, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Vendedor",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 12))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("CPF Vendedor");

		try {
			txtfCPFVend.setFormatterFactory(
					new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		txtfCPFVend.setEnabled(false);

		lblVendedor.setText(" ");
		lblVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		btnConsultarVen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnConsultarVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/pesq.png"))); // NOI18N
		btnConsultarVen.setEnabled(false);
		btnConsultarVen.setMaximumSize(new java.awt.Dimension(49, 20));
		btnConsultarVen.setMinimumSize(new java.awt.Dimension(49, 20));
		btnConsultarVen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarVenActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
								.addGap(8, 8, 8)
								.addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(txtfCPFVend, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnConsultarVen, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 490,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addGap(15, 15, 15)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(txtfCPFVend, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(lblVendedor, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnConsultarVen,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addContainerGap(15, Short.MAX_VALUE)));

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens do Pedido",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 12))); // NOI18N

		lblProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel6.setText("Qtde. Vendida");

		txtCodProduto.setEnabled(false);

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel5.setText("Código Produto");

		btnAddItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/add.png"))); // NOI18N
		btnAddItem.setText("Adicionar Item");
		btnAddItem.setEnabled(false);
		btnAddItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddItemActionPerformed(evt);
			}
		});

		btnRemoverItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/rem.png"))); // NOI18N
		btnRemoverItem.setText("Remover Item");
		btnRemoverItem.setEnabled(false);
		btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRemoverItemActionPerformed(evt);
			}
		});

		tblItens.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				},
				new String[] {
						"Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "SubTotal"
				}) {
			Class[] types = new Class[] {
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class
			};
			boolean[] canEdit = new boolean[] {
					false, false, false, false, false
			};

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tblItens);
		if (tblItens.getColumnModel().getColumnCount() > 0) {
			tblItens.getColumnModel().getColumn(1).setResizable(false);
			tblItens.getColumnModel().getColumn(2).setResizable(false);
			tblItens.getColumnModel().getColumn(3).setResizable(false);
		}

		lblValTotPedido.setText(" ");
		lblValTotPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel12.setText("Valor Total do Pedido");

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel13.setText("Quantidade de Itens do Pedido");

		lblQtdItensPedido.setText(" ");
		lblQtdItensPedido
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		txtQtdItensPedido.setEnabled(false);

		btnConsultarPro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnConsultarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/Icon/pesq.png"))); // NOI18N
		btnConsultarPro.setEnabled(false);
		btnConsultarPro.setMaximumSize(new java.awt.Dimension(49, 20));
		btnConsultarPro.setMinimumSize(new java.awt.Dimension(49, 20));
		btnConsultarPro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsultarProActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
												.createSequentialGroup()
												.addGap(0, 329, Short.MAX_VALUE)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout.createSequentialGroup()
																		.addGroup(jPanel4Layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(jLabel13)
																				.addComponent(jLabel12))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(jPanel4Layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(lblValTotPedido,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						116, Short.MAX_VALUE)
																				.addComponent(lblQtdItensPedido,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																		.addContainerGap())
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout.createSequentialGroup()
																		.addGroup(jPanel4Layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(lblProduto,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						225,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(btnAddItem,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						195,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(jPanel4Layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(btnRemoverItem,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						195,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						jPanel4Layout
																								.createSequentialGroup()
																								.addComponent(jLabel6)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										txtQtdItensPedido,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										80,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(18, 18, 18))))
										.addGroup(jPanel4Layout.createSequentialGroup()
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addGap(5, 5, 5)
																.addComponent(jScrollPane1))
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addComponent(jLabel5)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(txtCodProduto,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 124,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(btnConsultarPro,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(0, 0, Short.MAX_VALUE)))
												.addContainerGap()))));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel4Layout.createSequentialGroup()
														.addGap(1, 1, 1)
														.addGroup(jPanel4Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(jPanel4Layout.createSequentialGroup()
																		.addComponent(jLabel5)
																		.addGap(5, 5, 5))
																.addComponent(btnConsultarPro,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 22,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblProduto, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 23,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(txtQtdItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnAddItem)
										.addComponent(btnRemoverItem))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel12)
										.addComponent(lblValTotPedido))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel13)
										.addComponent(lblQtdItensPedido))
								.addGap(31, 31, 31)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(16, 16, 16)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup()
												.addGap(0, 0, Short.MAX_VALUE)
												.addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(15, 15, 15)
												.addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(15, 15, 15)
												.addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(15, 15, 15)
												.addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(16, 16, 16)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnIncluir)
										.addComponent(btnSair)
										.addComponent(btnExcluir)
										.addComponent(btnAlterar))
								.addContainerGap(15, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		conexao = new Conexao("db_nicolas", "admin"); // usuario e senha
		conexao.setDriver("oracle.jdbc.driver.OracleDriver");
		conexao.setConnectionString("jdbc:oracle:thin:@127.0.0.1:1521:xe");
		daoItemPedido = new DaoItemPedido(conexao.conectar());
		daoPedido = new DaoPedido(conexao.conectar());
                daoCliente = new DaoCliente(conexao.conectar());
                daoVendedor = new DaoVendedor(conexao.conectar());
                daoProduto = new DaoProduto(conexao.conectar());
                
	}// GEN-LAST:event_formWindowOpened

	private void btnConsultarPedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultarPedActionPerformed
		String codPedido = txtNumPedido.getText();
		if (codPedido == null || codPedido.isEmpty() || !codPedido.matches("^\\d+$")) {
			JOptionPane.showMessageDialog(this, "Numero do pedido inválido!", "Pedido", JOptionPane.WARNING_MESSAGE);
			txtNumPedido.requestFocus();
			return;
		}
		pedido = null;
		 pedido = daoPedido.consultar(txtNumPedido.getText());

		if (pedido == null) {
			txtNumPedido.setEnabled(false);
			txtfDtPedido.setEnabled(true);
			btnConsultarPed.setEnabled(false);
			txtCodProduto.setEnabled(false);
			rbtnAVista.setEnabled(true);
			rbtnAPrazo.setEnabled(true);
			txtfCPFCli.setEnabled(true);
			btnConsultarCli.setEnabled(true);
			btnAlterar.setEnabled(false);
			btnExcluir.setEnabled(false);
        btnIncluir.setEnabled(true);
		} else {
			txtfDtPedido.setText(pedido.getDataEmissao());
			txtfCPFCli.setText(pedido.getCliente().getCpf());
			txtfCPFVend.setText(pedido.getVendedor().getCpf());
			lblVendedor.setText(pedido.getVendedor().getNome());
			lblCliente.setText(pedido.getCliente().getNome());

			btnConsultarPed.setEnabled(false);
			txtCodProduto.setEnabled(true);
                        btnConsultarPro.setEnabled(true);
			btnAlterar.setEnabled(true);
			btnExcluir.setEnabled(true);
			btnRemoverItem.setEnabled(true);
                        txtfCPFCli.setEnabled(true);
                        btnConsultarCli.setEnabled(true);
                        txtfCPFVend.setEnabled(true);
                        btnConsultarVen.setEnabled(true);
                        rbtnAPrazo.setEnabled(true);
                        rbtnAVista.setEnabled(true);
                        txtfDtPedido.setEnabled(true);
                        btnAddItem.setEnabled(true);
                        
                        itemPedido = null;
                        itensPedido = null;
            itensPedido = new ArrayList(pedido.getItensPedido());
            cliente = pedido.getCliente();
            vendedor = pedido.getVendedor();
        btnIncluir.setEnabled(false);

            atualizarListaDeProdutos();
		}

	}// GEN-LAST:event_btnConsultarPedActionPerformed

	private void btnConsultarCliActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultarCliActionPerformed
		cliente = null;
		String cpfCliente = txtfCPFCli.getText().replaceAll("[.-]", "");
		if (!Pessoa.validarCPF(cpfCliente)) {
			JOptionPane.showMessageDialog(this, "CPF invalido inválido!", "Cliente", JOptionPane.WARNING_MESSAGE);
			txtfCPFCli.requestFocus();
			return;
		}

		if (!validarData(txtfDtPedido.getText())) {
			JOptionPane.showMessageDialog(this, "Data inválida!", "Pedido", 2);
			txtfDtPedido.requestFocus();
			return;
		}
		pedido = new Pedido(txtNumPedido.getText(), txtfDtPedido.getText());

		 cliente = daoCliente.consultar(cpfCliente);
		//cliente = new Cliente(cpfCliente, "nome cliente", 500.0);

		if (cliente == null) {
			JOptionPane.showMessageDialog(this, "Cliente não encontrado.", "Cliente", JOptionPane.WARNING_MESSAGE);
			txtfCPFCli.requestFocus();
			txtfCPFCli.setText("");
		} else {
			lblCliente.setText(cliente.getNome());

			txtfCPFCli.setEnabled(false);
			txtfDtPedido.setEnabled(false);
			btnConsultarCli.setEnabled(false);
			txtfCPFVend.setEnabled(true);
			btnConsultarVen.setEnabled(true);
			txtfCPFVend.requestFocus();
			pedido.setCliente(cliente);
		}
	}// GEN-LAST:event_btnConsultarCliActionPerformed

	private void btnConsultarVenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultarVenActionPerformed
		vendedor = null;
		String cpfCVendedor = txtfCPFVend.getText().replaceAll("[.-]", "");

		if (!Pessoa.validarCPF(cpfCVendedor)) {
			JOptionPane.showMessageDialog(this, "CPF invalido inválido!", "Vendedor", JOptionPane.WARNING_MESSAGE);
			txtfCPFVend.requestFocus();
			return;
		}
		 vendedor = daoVendedor.consultar(cpfCVendedor);
		//vendedor = new Vendedor(cpfCVendedor, "nome vendedor", 1000.0);

		if (vendedor == null) {
			JOptionPane.showMessageDialog(this, "Vendedor não encontrado.", "Vendedor", JOptionPane.WARNING_MESSAGE);
			txtfCPFVend.requestFocus();
			txtfCPFVend.setText("");
		} else {
			lblVendedor.setText(vendedor.getNome());
			txtfCPFVend.setEnabled(false);
			btnConsultarVen.setEnabled(false);
			txtCodProduto.setEnabled(true);
			btnConsultarPro.setEnabled(true);
			txtCodProduto.requestFocus();

			pedido.setVendedor(vendedor);
		}
	}// GEN-LAST:event_btnConsultarVenActionPerformed

	private void btnConsultarProActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsultarProActionPerformed
		String codProduto = txtCodProduto.getText();
		if (codProduto == null || codProduto.isEmpty() || !codProduto.matches("^\\d+$")) {
			JOptionPane.showMessageDialog(this, "Código do produto inválido!", "Produto", JOptionPane.WARNING_MESSAGE);
			txtNumPedido.requestFocus();
			return;
		}
		produto = null;
		 produto = daoProduto.consultar(codProduto);

		if (produto == null) {
			JOptionPane.showMessageDialog(this, "Produto não encontrado", "Produto", JOptionPane.WARNING_MESSAGE);
			txtCodProduto.setText("");
			txtCodProduto.requestFocus();

			btnAddItem.setEnabled(false);
			btnRemoverItem.setEnabled(false);
			txtQtdItensPedido.setEnabled(false);
		} else {
			lblProduto.setText(produto.getDescricao());
			txtQtdItensPedido.setEnabled(true);
			txtQtdItensPedido.requestFocus();

			btnAddItem.setEnabled(true);
			btnRemoverItem.setEnabled(true);
		}
	}// GEN-LAST:event_btnConsultarProActionPerformed

	private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddItemActionPerformed
            System.out.println("passou aqui hehe");
		String qtdVendida = txtQtdItensPedido.getText().replace(",", ".");
		if (qtdVendida == null || qtdVendida.isEmpty() || !qtdVendida.matches("^\\d+$")
				|| Double.parseDouble(qtdVendida) <= 0) {
			JOptionPane.showMessageDialog(this, "Quantidade inválida inválido!", "Item Pedido",
					JOptionPane.WARNING_MESSAGE);
			txtNumPedido.requestFocus();
			return;
		}
		Double numQtdVendida = Double.parseDouble(qtdVendida);
		if (numQtdVendida > produto.getQtdeEstoque()) {
			JOptionPane.showMessageDialog(this, "Quantidade de estoque insuficiente");
			txtQtdItensPedido.setText("");
			txtQtdItensPedido.requestFocus();
		} else if (numQtdVendida * produto.getPreco() > cliente.getLimiteDisp()) {
			JOptionPane.showMessageDialog(this, "Limite do cliente indisponível.\nLimite disponível: "
					+ String.format("%.2f", cliente.getLimiteDisp()));
			txtQtdItensPedido.setText("");
			txtQtdItensPedido.requestFocus();
		} else {
                        Random random = new Random();
			itemPedido = new ItemPedido(random.nextInt(99999), numQtdVendida, produto);
                        System.out.println(itensPedido.size() + 1);
			pedido.addItemPedido(itemPedido);
			itensPedido.add(itemPedido);

			atualizarListaDeProdutos();
		}
	}// GEN-LAST:event_btnAddItemActionPerformed

	private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRemoverItemActionPerformed
		if (tblItens.getSelectedRow() == -1) {
			JOptionPane.showMessageDialog(this, "Selecione uma linha", "Produtos", JOptionPane.WARNING_MESSAGE);
		} else {
                    System.out.println("remover");
                    System.out.println(itensPedido.size());
                    System.out.println(tblItens.getSelectedRow());
			ItemPedido itemPedidoParRemover = itensPedido.get(tblItens.getSelectedRow());

			pedido.removerItemPedido(itemPedidoParRemover);
                        System.out.println("asdsada");
                    System.out.println(itensPedido.size());
                    System.out.println(tblItens.getSelectedRow());
			itensPedido.remove(tblItens.getSelectedRow());
                        System.out.println("1234");
                    System.out.println(itensPedido.size());
                    System.out.println(tblItens.getSelectedRow());
			atualizarListaDeProdutos();
		}
	}// GEN-LAST:event_btnRemoverItemActionPerformed

	private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIncluirActionPerformed
		System.out.println("==== PEDIDO ====");
		pedido.setFormaPagto(rbtnAVista.isSelected());

		System.out.println(pedido.getNumero());
		System.out.println(pedido.getDataEmissao());
		System.out.println(pedido.getDataPagto());
		System.out.println(pedido.getSituacao());
		System.out.println(pedido.getCliente().getCpf());
		System.out.println(pedido.getVendedor().getCpf());
		System.out.println("==== ITENS PEDIDO ====");
		 daoPedido.inserir(pedido);
		for (ItemPedido elementoItemPedido : itensPedido) {
			System.out.println(elementoItemPedido.getSequencia());
			System.out.println(elementoItemPedido.getQtdeVendida());
			System.out.println(elementoItemPedido.getProduto());
			System.out.println(elementoItemPedido.getPedido().getNumero());
			 daoItemPedido.inserir(elementoItemPedido);
		}
                daoCliente.alterar(cliente);
        txtNumPedido.setText("");
        txtNumPedido.requestFocus();
        txtNumPedido.setEnabled(true);
        btnConsultarPed.setEnabled(true);

        txtfDtPedido.setText("");
        txtfDtPedido.setEnabled(false);    

        txtfCPFCli.setText("");
        txtfCPFCli.setEnabled(false);
        lblCliente.setText("");

        txtfCPFVend.setText("");
        txtfCPFVend.setEnabled(false);
        lblVendedor.setText("");

        txtCodProduto.setText("");
        txtCodProduto.setEnabled(false);
        lblProduto.setText("");

        txtQtdItensPedido.setText("");
        txtQtdItensPedido.setEnabled(false);
        btnConsultarPro.setEnabled(false);
        btnAddItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        lblValTotPedido.setText("");
        lblQtdItensPedido.setText("");

        btnIncluir.setEnabled(false);

        rbtnAPrazo.setEnabled(false);
        rbtnAVista.setEnabled(false);
        rbtnAVista.setSelected(true);

        itensPedido.clear();
        pedido = null;
        cliente = null;
        vendedor = null;
        produto = null;
        atualizarListaDeProdutos();
	}// GEN-LAST:event_btnIncluirActionPerformed

	private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Confirma Alteração?") == 0) {
            pedido.setDataPagto(txtfDtPedido.getText());
            pedido.setCliente(cliente);
            pedido.setVendedor(vendedor);
            pedido.setFormaPagto(rbtnAVista.isSelected());
            daoPedido.alterar(pedido);
            daoItemPedido.excluirItensDoPedido(pedido.getNumero());
            for (ItemPedido elementoItemPedido : itensPedido) {
			System.out.println(elementoItemPedido.getSequencia());
			System.out.println(elementoItemPedido.getQtdeVendida());
			System.out.println(elementoItemPedido.getProduto());
			System.out.println(elementoItemPedido.getPedido().getNumero());
			 daoItemPedido.inserir(elementoItemPedido);
		}
        txtNumPedido.setText("");
        txtNumPedido.requestFocus();
        txtNumPedido.setEnabled(true);
        btnConsultarPed.setEnabled(true);

        txtfDtPedido.setText("");
        txtfDtPedido.setEnabled(false);    

        txtfCPFCli.setText("");
        txtfCPFCli.setEnabled(false);
        lblCliente.setText("");

        txtfCPFVend.setText("");
        txtfCPFVend.setEnabled(false);
        lblVendedor.setText("");

        txtCodProduto.setText("");
        txtCodProduto.setEnabled(false);
        lblProduto.setText("");

        txtQtdItensPedido.setText("");
        txtQtdItensPedido.setEnabled(false);
        btnConsultarPro.setEnabled(false);
        btnAddItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        lblValTotPedido.setText("");
        lblQtdItensPedido.setText("");

        btnIncluir.setEnabled(false);

        rbtnAPrazo.setEnabled(false);
        rbtnAVista.setEnabled(false);
        rbtnAVista.setSelected(true);

        itensPedido.clear();
        pedido = null;
        cliente = null;
        vendedor = null;
        produto = null;
        atualizarListaDeProdutos();
        }       
    }// GEN-LAST:event_btnAlterarActionPerformed

	private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
            if (JOptionPane.showConfirmDialog(this, "Confirmar exclusao?") == 0) {
        daoPedido.excluir(pedido);

        txtNumPedido.setText("");
        txtNumPedido.requestFocus();
        txtNumPedido.setEnabled(true);
        btnConsultarPed.setEnabled(true);

        txtfDtPedido.setText("");
        txtfDtPedido.setEnabled(false);    

        txtfCPFCli.setText("");
        txtfCPFCli.setEnabled(false);
        lblCliente.setText("");

        txtfCPFVend.setText("");
        txtfCPFVend.setEnabled(false);
        lblVendedor.setText("");

        txtCodProduto.setText("");
        txtCodProduto.setEnabled(false);
        lblProduto.setText("");

        txtQtdItensPedido.setText("");
        txtQtdItensPedido.setEnabled(false);
        btnConsultarPro.setEnabled(false);
        btnAddItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        lblValTotPedido.setText("");
        lblQtdItensPedido.setText("");

        btnIncluir.setEnabled(false);

        rbtnAPrazo.setEnabled(false);
        rbtnAVista.setEnabled(false);
        rbtnAVista.setSelected(true);

        itensPedido.clear();
        pedido = null;
        cliente = null;
        vendedor = null;
        produto = null;
        atualizarListaDeProdutos();
        }
	}// GEN-LAST:event_btnExcluirActionPerformed

	private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
		dispose();
	}// GEN-LAST:event_btnSairActionPerformed

	private void atualizarListaDeProdutos() {
        Double qtdItensTotal = 0.0;
        Double total = 0.0;
		tableModel = (DefaultTableModel) tblItens.getModel();
		tableModel.setRowCount(0);
		for (ItemPedido elementoItemPedido : itensPedido) {
                    System.out.println(elementoItemPedido.getSequencia());
                    System.out.println(elementoItemPedido.getProduto().getDescricao());
			Double precoProduto = elementoItemPedido.getProduto().getPreco();
			Double subTotal = elementoItemPedido.getQtdeVendida() * precoProduto;
			String linha[] = {
					elementoItemPedido.getProduto().getCodigo(),
					elementoItemPedido.getProduto().getDescricao(),
					String.format("%.2f", precoProduto),
					Double.toString(elementoItemPedido.getQtdeVendida()),
					String.format("%.2f", subTotal)
			};
			tableModel.addRow(linha);
            qtdItensTotal += elementoItemPedido.getQtdeVendida();
            total += subTotal;
		}
        lblValTotPedido.setText(String.format("%.2f", total));
        lblQtdItensPedido.setText(String.format("%.2f", qtdItensTotal));
	}

	private boolean validarData(String dateStr) {
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		sdf.setLenient(false); // Define que a validação será estrita

		try {
			sdf.parse(dateStr);
			return true;
		} catch (Exception e) {
			return false;
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAddItem;
	private javax.swing.JButton btnAlterar;
	private javax.swing.JButton btnConsultarCli;
	private javax.swing.JButton btnConsultarPed;
	private javax.swing.JButton btnConsultarPro;
	private javax.swing.JButton btnConsultarVen;
	private javax.swing.JButton btnExcluir;
	private javax.swing.JButton btnIncluir;
	private javax.swing.JButton btnRemoverItem;
	private javax.swing.JButton btnSair;
	private javax.swing.ButtonGroup groupFormaPagamento;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblCliente;
	private javax.swing.JLabel lblProduto;
	private javax.swing.JLabel lblQtdItensPedido;
	private javax.swing.JLabel lblValTotPedido;
	private javax.swing.JLabel lblVendedor;
	private javax.swing.JRadioButton rbtnAPrazo;
	private javax.swing.JRadioButton rbtnAVista;
	private javax.swing.JTable tblItens;
	private javax.swing.JTextField txtCodProduto;
	private javax.swing.JTextField txtNumPedido;
	private javax.swing.JTextField txtQtdItensPedido;
	private javax.swing.JFormattedTextField txtfCPFCli;
	private javax.swing.JFormattedTextField txtfCPFVend;
	private javax.swing.JFormattedTextField txtfDtPedido;
	// End of variables declaration//GEN-END:variables
	private DaoPedido daoPedido = null;
	private DaoItemPedido daoItemPedido = null;
	private DaoCliente daoCliente = null;
	private DaoVendedor daoVendedor = null;
	private DaoProduto daoProduto = null;
	private ItemPedido itemPedido = null;
	private ArrayList<ItemPedido> itensPedido = new ArrayList<ItemPedido>();
	private Pedido pedido = null;
	private Cliente cliente = null;
	private Vendedor vendedor = null;
	private Produto produto = null;
	private Conexao conexao = null;
	private DefaultTableModel tableModel = null;
}
